title: FAA
email: info@faa.org.mz
description: >- # this means to ignore newlines until "baseurl:"
  Fundação Apoio Amigo
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Ivo Zinenda

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-paginate-v2

# Collections
collections_dir: collections
collections:
  sobre:

sass:
  sass_dir: assets/_sass
  style: compressed

pagination:
  enabled: true
  per_page: 10
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
