backend:
  name: git-gateway
  use_large_media_transforms_in_media_library: false

media_folder: 'assets/img/uploads'

site_url: https://faa.org.mz
logo_url: https://d33wubrfki0l68.cloudfront.net/f1afd154dd1bd09e6957dce7291bfc56834b4489/b2edb/assets/img/brand/logo.svg

show_preview_links: false

collections:
  - label: "Sobre"
    name: "sobre"
    folder: "collections/_sobre"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}

  - label: "Objectivos"
    name: "objectivos"
    folder: "collections/_objectivos"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Conteúdo", name: "body", widget: "markdown", required: false}

  - label: "Noticias"
    name: "noticias"
    folder: "collections/_posts/noticias"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Categoria", name: "category", default: "noticias", widget: "hidden"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Fotografia", name: "image", widget: "image"}
      - {label: "Artigo", name: "body", widget: "markdown"}

  - label: "Galeria"
    name: "galeria"
    folder: "collections/_galeria"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}

  - label: "Parceiros"
    name: "parceiros"
    folder: "collections/_parceiros"
    create: true
    fields:
      - {label: "Parceiros", name: "title", default: "Parceiros", widget: "string"}
      - label: "Parceiro"
        name: "parceiro"
        widget: "list"
        fields:
          - {label: "Empresa", name: "company", widget: "string"}
          - label: "Logotipo"
            name: "image"
            widget: "image"

  